USE WAREHOUSE LADE_LOGISTICS_WH;
USE DATABASE LADE_LOGISTICS_DW;
USE SCHEMA RAW;

SELECT  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
        CURRENT_DATABASE() AS CURRENT_DATABASE,
        CURRENT_SCHEMA() AS CURRENT_SCHEMA; 


-- File Format
CREATE FILE FORMAT IF NOT EXISTS LADE_CSV_FORMAT
TYPE ='CSV'
PARSE_HEADER = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

SHOW FILE FORMATS IN SCHEMA LADE_LOGISTICS_DW.RAW;

-- Stage Creation
CREATE STAGE IF NOT EXISTS LADE_DELIVERY_STAGE
FILE_FORMAT = (FORMAT_NAME = LADE_CSV_FORMAT);

SHOW STAGES IN LADE_LOGISTICS_DW.RAW;

LIST @LADE_DELIVERY_STAGE;

SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@LADE_DELIVERY_STAGE',
        FILE_FORMAT => 'LADE_CSV_FORMAT'
    )
);


CREATE OR REPLACE TABLE LADE_DELIVERY_RAW
USING TEMPLATE(
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(
            'COLUMN_NAME', COLUMN_NAME,
            'TYPE', TYPE,
            'NULLABLE', NULLABLE
        )
    )WITHIN GROUP(ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@LADE_DELIVERY_STAGE',
            FILE_FORMAT => 'LADE_CSV_FORMAT'    
        )
    )
);

DESC TABLE LADE_DELIVERY_RAW;

COPY INTO LADE_DELIVERY_RAW
FROM @LADE_DELIVERY_STAGE
FILE_FORMAT = (FORMAT_NAME =  LADE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';


SELECT * FROM LADE_DELIVERY_RAW
LIMIT 10;

SELECT COUNT(*) AS ROW_COUNT
FROM LADE_DELIVERY_RAW;


SELECT
    FILE_NAME,
    STATUS,
    ROW_COUNT,
    ROW_PARSED,
    FIRST_ERROR_MESSAGE,
    LAST_LOAD_TIME
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'LADE_LOGISTICS_DW.RAW.LADE_DELIVERY_RAW',
        START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;


SELECT SUM(ROW_COUNT) AS TOTAL_ROWS_LOADED
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'LADE_LOGISTICS_DW.RAW.LADE_DELIVERY_RAW',
        START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
);