-- Project Warehouse Creation
CREATE WAREHOUSE IF NOT EXISTS LADE_LOGISTICS_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED= TRUE;

USE WAREHOUSE LADE_LOGISTICS_WH;

-- Database Creation
CREATE DATABASE IF NOT EXISTS LADE_LOGISTICS_DW;

USE DATABASE LADE_LOGISTICS_DW;

-- Project Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS AUDIT;

SELECT CURRENT_WAREHOUSE(),CURRENT_DATABASE(),CURRENT_SCHEMA();

SHOW SCHEMAS IN DATABASE LADE_LOGISTICS_DW;